# Generated by Django 6.0.2 on 2026-02-16 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='pin',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
