# Generated by Django 6.0.2 on 2026-02-18 13:13

import client.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_customer_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='account_number',
            field=models.CharField(default=client.models.generateAccountNumber, editable=False, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='pin',
            field=models.CharField(blank=True, editable=False, max_length=128, null=True),
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=client.models.generateVoucherCode, max_length=12)),
                ('amount', models.FloatField()),
                ('is_loaded', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.customer')),
            ],
        ),
    ]
